import React, { useState } from 'react';
import { useData } from '../context/AppProvider';
import { Card, Button, Input } from '../components/ui';
import { Settings, Save, AlertTriangle } from 'lucide-react';
import { toast } from '../components/toast';
import { motion } from 'framer-motion';

const ServiceAdmin = () => {
  const { serviceCatalog, saveServiceCatalog } = useData();
  const [draft, setDraft] = useState(serviceCatalog);
  const [inventoryJson, setInventoryJson] = useState(JSON.stringify(serviceCatalog.inventory, null, 2));
  const [jsonError, setJsonError] = useState('');
  const [saving, setSaving] = useState(false);

  const handlePriceChange = (key, value) => {
    setDraft({ ...draft, [key]: Number(value) });
  };

  const handleJsonChange = (e) => {
    setInventoryJson(e.target.value);
    try {
      JSON.parse(e.target.value);
      setJsonError('');
    } catch {
      setJsonError('Invalid JSON format');
    }
  };

  const handleSave = async () => {
    try {
      if (jsonError) {
        toast.error('Please fix JSON errors before saving');
        return;
      }
      setSaving(true);
      const parsedInventory = JSON.parse(inventoryJson);
      const finalCatalog = { ...draft, inventory: parsedInventory };
      await saveServiceCatalog(finalCatalog);
      toast.success('Service catalog updated successfully!');
    } catch (error) {
      toast.error('Failed to save catalog.');
      console.error(error);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto pb-20">
      <div className="flex justify-between items-end mb-8 mt-4">
        <div>
          <h2 className="text-3xl font-black text-slate-900 flex items-center gap-3">
            <Settings className="text-primary-600" size={32} /> Service Catalog Admin
          </h2>
          <p className="text-slate-500 font-medium mt-2">Manage standard prices and inventory items</p>
        </div>
        <Button onClick={handleSave} disabled={saving || !!jsonError} className="bg-primary-600 hover:bg-primary-700 text-white rounded-xl shadow-md h-12 px-6">
          <Save size={18} className="mr-2" /> {saving ? 'Saving...' : 'Save Changes'}
        </Button>
      </div>

      <div className="grid md:grid-cols-2 gap-8">
        {/* Recommendation Base Prices */}
        <div className="space-y-6">
          <Card className="p-6 rounded-[2rem] shadow-lg border-slate-100">
            <h3 className="text-xl font-bold text-slate-900 mb-6 border-b border-slate-100 pb-4">Standard Base Prices</h3>
            <p className="text-sm text-slate-500 mb-6">These prices are used to automatically quote recommendations generated by the Vehicle Inspection module.</p>
            
            <div className="space-y-5">
              {[
                { key: 'tyreReplacement', label: 'Tyre Replacement (Default)' },
                { key: 'tyreRotation', label: 'Tyre Rotation & Balance' },
                { key: 'batteryReplacement', label: 'Battery Replacement (Default)' },
                { key: 'generalService', label: 'General Service & Alignment' },
              ].map(field => (
                <div key={field.key}>
                  <label className="block text-sm font-bold text-slate-700 mb-1">{field.label}</label>
                  <Input 
                    type="number"
                    value={draft[field.key]}
                    onChange={(e) => handlePriceChange(field.key, e.target.value)}
                    icon="₹"
                  />
                </div>
              ))}
            </div>
          </Card>
        </div>

        {/* Inventory JSON Editor */}
        <div className="space-y-6">
          <Card className="p-6 rounded-[2rem] shadow-lg border-slate-100 h-full flex flex-col">
            <h3 className="text-xl font-bold text-slate-900 mb-2">Inventory Data (JSON)</h3>
            <p className="text-sm text-slate-500 mb-4">Edit the raw catalog objects that populate the Service Selection screen.</p>
            
            <div className="flex-1 relative flex flex-col">
              <textarea 
                className={`w-full flex-1 min-h-[300px] p-4 font-mono text-sm bg-slate-800 text-emerald-400 rounded-xl outline-none focus:ring-2 focus:ring-primary-500 transition-all shadow-inner ${jsonError ? 'border-2 border-red-500' : 'border border-slate-700'}`}
                value={inventoryJson}
                onChange={handleJsonChange}
                spellCheck={false}
              />
              {jsonError && (
                <motion.div initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} className="absolute bottom-4 right-4 bg-red-100 text-red-700 px-3 py-1.5 rounded-lg text-sm font-bold flex items-center gap-2 shadow-sm">
                  <AlertTriangle size={16} /> {jsonError}
                </motion.div>
              )}
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default ServiceAdmin;
